name: dlox
description: An implementation of the Lox language in Dart.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.0

dependencies:
  dart_style: 2.0.3
  quiver: ^3.0.1
  recase: 4.0.0
